const mongoose = require('mongoose');
const College = require('./models/College');

// MongoDB Connection
const MONGODB_URI = 'mongodb+srv://chowdaryp697:prasanna@cluster0.pdtmjr8.mongodb.net/collegeportal';

// All course categories
const allCourses = [
  'mba', 'engineering', 'medical', 'design', 'law', 'hospitality-travel',
  'mass-communication-media', 'business-management', 'it-software',
  'humanities-social-science', 'arts', 'science', 'architecture-planning',
  'accounting-commerce', 'teaching-education', 'nursing'
];

// Karnataka Colleges Data
const collegesData = [
  { name: "IIM Bangalore - Indian Institute of Management", city: "Bangalore", rating: 4.9 },
  { name: "Indian Institute of Science, Department of Management Studies", city: "Bangalore", rating: 4.8 },
  { name: "National Law School of India University - NLSIU", city: "Bangalore", rating: 4.8 },
  { name: "TAPMI Manipal", city: "Manipal", rating: 4.6 },
  { name: "RR Group of Institutions", city: "Bangalore", rating: 4.2 },
  { name: "Surana College", city: "Bangalore", rating: 4.1 },
  { name: "Symbiosis Institute of Business Management - SIBM", city: "Bangalore", rating: 4.5 },
  { name: "Narsee Monjee Institute of Management Studies - NMIMS", city: "Bangalore", rating: 4.5 },
  { name: "Jagdish Sheth School of Management - JAGSOM", city: "Bangalore", rating: 4.4 },
  { name: "Prin. L.N. Welingkar Institute of Management Development & Research - WeSchool", city: "Bangalore", rating: 4.4 },
  { name: "Xavier Institute of Management and Entrepreneurship - XIME", city: "Bangalore", rating: 4.3 },
  { name: "Indus Business Academy - IBA", city: "Bangalore", rating: 4.2 },
  { name: "Kasturba Medical College - KMC Manipal", city: "Manipal", rating: 4.7 },
  { name: "Krupanidhi College of Management - KCM", city: "Bangalore", rating: 4.3 },
  { name: "AIMS Institutes", city: "Bangalore", rating: 4.2 },
  { name: "SDM Institute for Management Development - SDMIMD", city: "Mysore", rating: 4.4 },
  { name: "International School of Management Excellence - ISME", city: "Bangalore", rating: 4.3 },
  { name: "Visvesvaraya Technological University - VTU", city: "Belgaum", rating: 4.5 },
  { name: "National Institute of Fashion Technology - NIFT", city: "Bangalore", rating: 4.6 },
  { name: "Acharya Bangalore B-School - ABBS", city: "Bangalore", rating: 4.2 },
  { name: "Institute of Hotel Management - IHM", city: "Bangalore", rating: 4.4 },
  { name: "Welcomgroup Graduate School of Hotel Administration - WGSHA", city: "Manipal", rating: 4.5 },
  { name: "Manipal College of Dental Sciences - MCODS Mangalore", city: "Mangalore", rating: 4.5 },
  { name: "Manipal College of Dental Sciences - MCODS Manipal", city: "Manipal", rating: 4.5 },
  { name: "IBMR International Business School - IBMR-IBS", city: "Bangalore", rating: 4.1 },
  { name: "International School of Business & Media - ISB&M", city: "Bangalore", rating: 4.2 },
  { name: "St Joseph's Institute of Management - SJIM", city: "Bangalore", rating: 4.4 },
  { name: "St John's Medical College", city: "Bangalore", rating: 4.6 },
  { name: "Ramaiah Institute of Management Studies - RIMS", city: "Bangalore", rating: 4.3 },
  { name: "Mount Carmel College - MCC", city: "Bangalore", rating: 4.4 },
  { name: "Christ University", city: "Bangalore", rating: 4.5 },
  { name: "Ramaiah Institute of Management - RIM", city: "Bangalore", rating: 4.3 },
  { name: "Center for Management Studies, Jain University - CMSJU", city: "Bangalore", rating: 4.4 },
  { name: "Manipal Academy of Higher Education - MAHE", city: "Manipal", rating: 4.7 },
  { name: "Bapuji Dental College and Hospital - BDCH", city: "Davanagere", rating: 4.3 },
  { name: "St Joseph's University", city: "Bangalore", rating: 4.5 },
  { name: "National Institute of Technology - NITK Surathkal", city: "Mangalore", rating: 4.7 },
  { name: "Kasturba Medical College - KMC Mangalore", city: "Mangalore", rating: 4.7 },
  { name: "A B Shetty Memorial Institute of Dental Sciences - ABSMIDS", city: "Mangalore", rating: 4.4 },
  { name: "JSS Medical College and Hospital - JSSMCH", city: "Mysore", rating: 4.5 },
  { name: "Dayananda Sagar Business School - DSBS", city: "Bangalore", rating: 4.2 },
  { name: "SDM College of Dental Sciences and Hospital - SDMCDSH", city: "Dharwad", rating: 4.3 },
  { name: "Manipal College of Pharmaceutical Sciences - MCOPS", city: "Manipal", rating: 4.5 },
  { name: "Faculty of Dental Sciences, M. S. Ramaiah University", city: "Bangalore", rating: 4.4 },
  { name: "RV Institute of Management - RVIM", city: "Bangalore", rating: 4.3 },
  { name: "Army Institute of Hotel Management & Catering Technology - AIHMCT", city: "Bangalore", rating: 4.3 },
  { name: "Kristu Jayanti College - KJC", city: "Bangalore", rating: 4.4 },
  { name: "Institute of Health Management Research - IIHMR", city: "Bangalore", rating: 4.2 },
  { name: "Indian Institute of Journalism and New Media - IIJNM", city: "Bangalore", rating: 4.4 },
  { name: "Presidency College", city: "Bangalore", rating: 4.2 },
  { name: "Ramaiah Medical College", city: "Bangalore", rating: 4.5 },
  { name: "Kirloskar Institute of Management - KIM", city: "Davanagere", rating: 4.1 },
  { name: "St. Aloysius College", city: "Mangalore", rating: 4.4 },
  { name: "International School of Business and Research - ISBR Business School", city: "Bangalore", rating: 4.2 },
  { name: "Jyoti Nivas College - JNC", city: "Bangalore", rating: 4.3 },
  { name: "The Oxford College of Science - TOCS", city: "Bangalore", rating: 4.1 },
  { name: "Presidency University, School of Management", city: "Bangalore", rating: 4.3 },
  { name: "JSS Academy of Higher Education & Research", city: "Mysore", rating: 4.5 },
  { name: "St. Joseph's College of Commerce - SJCC", city: "Bangalore", rating: 4.5 },
  { name: "Bangalore Medical College and Research Institute - BMCRI", city: "Bangalore", rating: 4.6 },
  { name: "Army Institute of Fashion and Design - AIFD", city: "Bangalore", rating: 4.2 },
  { name: "JD Institute of Fashion Technology", city: "Bangalore", rating: 4.1 },
  { name: "St Aloysius Institute of Management and Information Technology - AIMIT", city: "Mangalore", rating: 4.3 },
  { name: "KLS Institute of Management Education & Research - KLS IMER", city: "Belgaum", rating: 4.2 },
  { name: "College of Dental Sciences Davanagere", city: "Davanagere", rating: 4.2 },
  { name: "BLDE Association's AS Patil College of Commerce", city: "Bijapur", rating: 4.0 },
  { name: "NMKRV College for Women", city: "Bangalore", rating: 4.1 },
  { name: "Adarsh Institute of Management and Information Technology - AIMIT", city: "Bangalore", rating: 4.0 },
  { name: "BMS School of Architecture - BMSSA", city: "Bangalore", rating: 4.3 },
  { name: "KS Hegde Medical Academy - KSHEMA", city: "Mangalore", rating: 4.4 },
  { name: "Krupanidhi Group of Institutions", city: "Bangalore", rating: 4.2 },
  { name: "Manipal Institute of Technology - MIT", city: "Manipal", rating: 4.7 },
  { name: "School of Law, Christ University - SLCU", city: "Bangalore", rating: 4.5 },
  { name: "Manipal School of Architecture and Planning - MSAP", city: "Manipal", rating: 4.4 },
  { name: "Vivekananda Degree College", city: "Bangalore", rating: 4.0 },
  { name: "School of Planning and Architecture, University of Mysore - SPA", city: "Mysore", rating: 4.3 },
  { name: "CMR Center for Business Studies - CMRCBS", city: "Bangalore", rating: 4.1 },
  { name: "Global Business School - GBS Hubli", city: "Hubli", rating: 4.0 },
  { name: "The Oxford College of Business Management", city: "Bangalore", rating: 4.1 },
  { name: "Chetan Business School", city: "Hubli", rating: 3.9 },
  { name: "M.S. Ramaiah College of Law - MSRCL", city: "Bangalore", rating: 4.2 },
  { name: "University College of Law Bangalore University", city: "Bangalore", rating: 4.3 },
  { name: "Belagavi Institute of Medical Sciences - BIMS", city: "Belagavi", rating: 4.3 },
  { name: "Bharatesh Education Trust's Global Business School - BETGBS", city: "Belgaum", rating: 4.0 },
  { name: "Jawaharlal Nehru Medical College - JNMC", city: "Belagavi", rating: 4.5 },
  { name: "Indian Academy Group of Institutions - IAGI", city: "Bangalore", rating: 4.1 },
  { name: "T John College - TJC", city: "Bangalore", rating: 4.1 },
  { name: "Institute of Business Management and Research - IBMR Hubli", city: "Hubli", rating: 4.0 },
  { name: "Coorg Institute of Dental Sciences - CIDS", city: "Kodagu", rating: 4.1 },
  { name: "Maharani Lakshmi Ammanni College for Women - MLACW", city: "Bangalore", rating: 4.2 },
  { name: "Seshadripuram Institute of Management Studies - SIMS", city: "Bangalore", rating: 4.1 },
  { name: "R V College of Engineering - RVCE", city: "Bangalore", rating: 4.6 },
  { name: "Ramaiah Institute of Technology - RIT", city: "Bangalore", rating: 4.5 },
  { name: "SDM College Ujire", city: "Mangalore", rating: 4.2 },
  { name: "RV College of Architecture - RVCA", city: "Bangalore", rating: 4.3 },
  { name: "Bangalore Institute of Legal Studies - BILS", city: "Bangalore", rating: 4.1 },
  { name: "International Institute of Information Technology - IIIT-B", city: "Bangalore", rating: 4.7 },
  { name: "BMS College of Engineering - BMSCE", city: "Bangalore", rating: 4.6 },
  { name: "The National Degree College", city: "Bangalore", rating: 4.1 },
  { name: "KLE University's College of Pharmacy Belgaum", city: "Belgaum", rating: 4.3 },
  { name: "K.L.E. Society's S.A. Manvi Law College", city: "Gadag", rating: 4.0 },
  { name: "KLE Society's Law College", city: "Bangalore", rating: 4.2 },
  { name: "MES College of Arts, Commerce & Science", city: "Bangalore", rating: 4.0 },
  { name: "Maratha Mandal College of Pharmacy", city: "Belgaum", rating: 4.1 },
  { name: "Seshadripuram College", city: "Bangalore", rating: 4.1 },
  { name: "IFIM College", city: "Bangalore", rating: 4.2 },
  { name: "Siddaganga Institute of Technology - SIT", city: "Tumkur", rating: 4.4 },
  { name: "St George College of Management Science and Nursing", city: "Bangalore", rating: 4.0 },
  { name: "Administrative Management College - AMC", city: "Bangalore", rating: 4.0 },
  { name: "CMR University - CMRU", city: "Bangalore", rating: 4.1 },
  { name: "The Oxford Dental College and Hospital", city: "Bangalore", rating: 4.2 },
  { name: "Sri Bhagawan Mahaveer Jain College", city: "Bangalore", rating: 4.1 },
  { name: "Global Institute of Management Sciences - GIMS", city: "Bangalore", rating: 4.0 },
  { name: "International Institute of Business Studies - IIBS", city: "Bangalore", rating: 4.1 },
  { name: "AJ Aviation Academy", city: "Bangalore", rating: 4.0 },
  { name: "Ramaiah College of Arts, Science and Commerce - RCASC", city: "Bangalore", rating: 4.2 },
  { name: "CMR Institute of Management Studies - CMRIMS", city: "Bangalore", rating: 4.1 },
  { name: "NITTE School of Management - NSOM", city: "Bangalore", rating: 4.2 },
  { name: "SDM Law College Kodialbail", city: "Mangalore", rating: 4.1 },
  { name: "Jain University - JU", city: "Bangalore", rating: 4.4 },
  { name: "New Horizon College of Engineering - NHCE", city: "Bangalore", rating: 4.2 },
  { name: "Faculty of Engineering and Technology, Jain University", city: "Bangalore", rating: 4.3 },
  { name: "Agriculture and Food Management Institute - AFMI", city: "Mysore", rating: 4.0 },
  { name: "Sri Jayachamarajendra College of Engineering - SJCE", city: "Mysore", rating: 4.3 },
  { name: "Poornaprajna Institute of Management - PIM", city: "Udupi", rating: 4.1 },
  { name: "Dayananda Sagar College of Engineering - DSCE", city: "Bangalore", rating: 4.3 },
  { name: "NMAM Institute of Technology - NMAMIT", city: "Udupi", rating: 4.3 },
  { name: "Bengaluru Law College", city: "Bangalore", rating: 4.1 },
  { name: "Central Food Technological Research Institute - CFTRI", city: "Mysore", rating: 4.4 },
  { name: "DA Pandu Memorial RV Dental College and Hospital", city: "Bangalore", rating: 4.2 },
  { name: "Yenepoya Dental College - YDC", city: "Mangalore", rating: 4.3 },
  { name: "The Nitte Gulabi Shetty Memorial Institute of Pharmaceutical Sciences", city: "Mangalore", rating: 4.2 },
  { name: "Nitte Meenakshi Institute of Technology - NMIT", city: "Bangalore", rating: 4.4 },
  { name: "KLE Society's S. Nijalingappa College - KLESNC", city: "Bangalore", rating: 4.1 },
  { name: "PES University - PESU", city: "Bangalore", rating: 4.6 },
  { name: "Indian Institute of Horticultural Research - IIHR", city: "Bangalore", rating: 4.3 },
  { name: "AJ Institute of Management - AJIM", city: "Mangalore", rating: 4.0 },
  { name: "National Research Centre for Cashew - NRCC", city: "Puttur", rating: 4.0 },
  { name: "Sambhram Academy of Management Studies - SAMS", city: "Bangalore", rating: 4.0 },
  { name: "National Institute of Animal Nutrition and Physiology - NIANP", city: "Bangalore", rating: 4.1 },
  { name: "ITM Business School Hullimavu", city: "Bangalore", rating: 4.0 },
  { name: "BMS Institute of Technology and Management - BMSIT", city: "Bangalore", rating: 4.4 },
  { name: "B. N. M. Institute of Technology - BNMIT", city: "Bangalore", rating: 4.3 },
  { name: "KLE Technological University", city: "Hubli", rating: 4.4 },
  { name: "Presidency Business School", city: "Bangalore", rating: 4.1 },
  { name: "Dr. Ambedkar Institute of Technology - AIT", city: "Bangalore", rating: 4.2 },
  { name: "PES College of Engineering - PESCE", city: "Mandya", rating: 4.2 },
  { name: "CMR Institute of Technology - CMRIT", city: "Bangalore", rating: 4.2 },
  { name: "The National Institute of Engineering - NIE", city: "Mysore", rating: 4.4 },
  { name: "Alliance College of Engineering and Design", city: "Bangalore", rating: 4.3 },
  { name: "Veterinary College Bangalore", city: "Bangalore", rating: 4.2 },
  { name: "Basaveshwar Engineering College - BEC", city: "Bagalkot", rating: 4.1 },
  { name: "Karnataka Veterinary Animal and Fisheries Sciences University", city: "Bidar", rating: 4.1 },
  { name: "University College of Law, Karnatak University", city: "Dharwad", rating: 4.2 },
  { name: "National Bureau of Agricultural Insect Resources - NBAIR", city: "Bangalore", rating: 4.0 },
  { name: "Al-Ameen College of Education", city: "Bangalore", rating: 4.0 },
  { name: "Indian Institute of Plantation Management - IIPM", city: "Bangalore", rating: 4.1 },
  { name: "Vaikunta Baliga College of Law - VBCLAW", city: "Udupi", rating: 4.0 },
  { name: "Hurakadli Ajja Law College", city: "Dharwad", rating: 4.0 },
  { name: "University of Agricultural Sciences - UAS Raichur", city: "Raichur", rating: 4.1 },
  { name: "Garden City University - GCU", city: "Bangalore", rating: 4.1 },
  { name: "University of Horticultural Sciences - UHS", city: "Bagalkot", rating: 4.1 },
  { name: "Acharya College of Education - ACE", city: "Bangalore", rating: 4.0 },
  { name: "Krishnadevaraya College of Dental Sciences & Hospital", city: "Bangalore", rating: 4.1 },
  { name: "Shree Devi College of Hotel Management", city: "Mangalore", rating: 4.0 },
  { name: "M Krishna Law College", city: "Hassan", rating: 3.9 },
  { name: "KLE Society's Institute of Hotel Management and Catering Technology", city: "Bangalore", rating: 4.1 },
  { name: "Rai Technology University - RTU", city: "Bangalore", rating: 4.0 },
  { name: "Seshadripuram Law College", city: "Bangalore", rating: 4.0 },
  { name: "Vidyavardhaka Law College - VLC", city: "Mysore", rating: 4.0 },
  { name: "Acharya & BM Reddy College of Pharmacy - ABMRCP", city: "Bangalore", rating: 4.1 },
  { name: "Sarada Vilas Law College", city: "Mysore", rating: 4.0 },
  { name: "International Institute of Hotel Management - IIHM", city: "Bangalore", rating: 4.2 },
  { name: "University of Agricultural and Horticultural Sciences - UAHS", city: "Bangalore", rating: 4.1 },
  { name: "Al-Ameen College of Pharmacy", city: "Bangalore", rating: 4.1 },
  { name: "University of Agricultural Sciences - UAS Dharwad", city: "Dharwad", rating: 4.2 },
  { name: "JSS Dental College and Hospital - JSSDCH", city: "Mysore", rating: 4.3 },
  { name: "University Visvesvaraya College of Engineering - UVCE", city: "Bangalore", rating: 4.4 },
  { name: "Indian Institute of Science - IISc", city: "Bangalore", rating: 4.9 },
  { name: "REVA University", city: "Bangalore", rating: 4.2 },
  { name: "Sambhram College of Hotel Management - SCHM", city: "Kolar", rating: 4.0 },
  { name: "Alliance University", city: "Bangalore", rating: 4.4 },
  { name: "Acharya Institute of Technology - AIT", city: "Bangalore", rating: 4.2 },
  { name: "MVJ College of Engineering - MVJCE", city: "Bangalore", rating: 4.2 },
  { name: "Presidency University", city: "Bangalore", rating: 4.3 },
  { name: "Azim Premji University", city: "Bangalore", rating: 4.5 },
  { name: "IIT Dharwad - Indian Institute of Technology", city: "Dharwad", rating: 4.7 },
  { name: "Dayanand Sagar College of Dental Sciences", city: "Bangalore", rating: 4.3 },
  { name: "Osteen College", city: "Bangalore", rating: 4.0 },
  { name: "Bangalore Institute of Technology - BIT", city: "Bangalore", rating: 4.3 },
  { name: "Nettur Technical Training Foundation - NTTF", city: "Bangalore", rating: 4.2 },
  { name: "Bangalore City College of Education", city: "Bangalore", rating: 4.0 },
  { name: "Bengaluru North University - BNU", city: "Kolar", rating: 4.0 },
  { name: "AMC Engineering College - AMC", city: "Bangalore", rating: 4.0 },
  { name: "Karavali College", city: "Mangalore", rating: 4.0 },
  { name: "Global Academy of Technology - GAT", city: "Bangalore", rating: 4.1 },
  { name: "HKBK Group of Institutions", city: "Bangalore", rating: 4.0 },
  { name: "KLE University", city: "Belgaum", rating: 4.4 },
  { name: "Indian Institute of Information Technology - IIITD Dharwad", city: "Dharwad", rating: 4.3 },
  { name: "Cambridge Institute of Technology - CiTech", city: "Bangalore", rating: 4.1 },
  { name: "GITAM Bangalore", city: "Bangalore", rating: 4.3 },
  { name: "Yenepoya University", city: "Mangalore", rating: 4.4 },
  { name: "HKE Society SNijalingappa Institute of Dental Science and Research", city: "Gulbarga", rating: 4.0 },
  { name: "ACS College of Engineering - ACSCE", city: "Bangalore", rating: 4.0 },
  { name: "Atria Institute of Technology", city: "Bangalore", rating: 4.1 },
  { name: "RNS Institute of Technology - RNSIT", city: "Bangalore", rating: 4.3 },
  { name: "Sir M Visvesvaraya Institute of Technology - Sir MVIT", city: "Bangalore", rating: 4.2 },
  { name: "Nitte University", city: "Mangalore", rating: 4.4 },
  { name: "Canara Engineering College - CEC", city: "Mangalore", rating: 4.0 },
  { name: "East West Institute of Technology - EWIT", city: "Bangalore", rating: 4.0 },
  { name: "Malnad College of Engineering - MCE", city: "Hassan", rating: 4.2 },
  { name: "Vemana Institute of Technology", city: "Bangalore", rating: 4.0 },
  { name: "Symbiosis International University - SIUB", city: "Bangalore", rating: 4.5 },
  { name: "Dayananda Sagar University - DSU", city: "Bangalore", rating: 4.2 },
  { name: "Sambhram Institute of Technology - SAIT", city: "Bangalore", rating: 4.0 },
  { name: "SJB Institute of Technology - SJBIT", city: "Bangalore", rating: 4.1 },
  { name: "The Oxford College of Engineering", city: "Bangalore", rating: 4.1 },
  { name: "Vidyavardhaka College of Engineering - VVCE", city: "Mysore", rating: 4.2 },
  { name: "Amrita Vishwa Vidyapeetham Bengaluru Campus", city: "Bangalore", rating: 4.5 },
  { name: "Sharnbasva University", city: "Gulbarga", rating: 4.0 },
  { name: "JSS Science and Technology University - JSSSTU", city: "Mysore", rating: 4.4 },
  { name: "City Engineering College - CEC", city: "Bangalore", rating: 4.0 },
  { name: "Sai Vidya Institute of Technology - SVIT", city: "Bangalore", rating: 4.0 },
  { name: "M.S. Ramaiah University of Applied Sciences - MSRUAS", city: "Bangalore", rating: 4.4 },
  { name: "Srinivas University", city: "Mangalore", rating: 4.2 },
  { name: "East West College of Engineering - EWCE", city: "Bangalore", rating: 4.0 },
  { name: "Adichunchanagiri University - ACU", city: "Mandya", rating: 4.1 },
  { name: "Indian Institute of Information Technology - IIIT Raichur", city: "Raichur", rating: 4.2 },
  { name: "Dayananda Sagar Academy of Technology and Management - DSATM", city: "Bangalore", rating: 4.1 },
  { name: "Don Bosco Institute of Technology - DBIT", city: "Bangalore", rating: 4.1 },
  { name: "Sri Krishna Institute of Technology - SKIT", city: "Bangalore", rating: 4.0 },
  { name: "BLDE University", city: "Bijapur", rating: 4.1 },
  { name: "K.S. School of Engineering and Management - KSSEM", city: "Bangalore", rating: 4.1 },
  { name: "JSS Academy of Technical Education - JSSATE", city: "Bangalore", rating: 4.2 },
  { name: "SDM College of Engineering and Technology - SDMCET", city: "Dharwad", rating: 4.2 },
  { name: "East Point Group of Institutions - EPGI", city: "Bangalore", rating: 4.0 },
  { name: "PA College of Engineering - PACE", city: "Mangalore", rating: 4.1 },
  { name: "Sri Venkateshwara College of Engineering - SVCE", city: "Bangalore", rating: 4.0 },
  { name: "APS College of Engineering - APS", city: "Bangalore", rating: 4.0 },
  { name: "KLS Gogte Institute of Technology - KLS GIT", city: "Belgaum", rating: 4.2 },
  { name: "Amrita School of Engineering - ASE", city: "Bangalore", rating: 4.3 },
  { name: "RajaRajeswari College of Engineering - RRCE", city: "Bangalore", rating: 4.0 },
  { name: "Bangalore Institute of Management Studies - BIMS", city: "Bangalore", rating: 4.1 },
  { name: "ISMS Business School - ISMSBS", city: "Bangalore", rating: 4.0 },
  { name: "Institute of Wood Science and Technology - IWST", city: "Bangalore", rating: 4.0 },
  { name: "Bangalore College of Engineering and Technology - BCET", city: "Bangalore", rating: 4.0 },
  { name: "Sapthagiri NPS University", city: "Bangalore", rating: 4.1 },
  { name: "Sri Siddhartha Institute of Technology - SSIT", city: "Tumkur", rating: 4.1 },
  { name: "Jyothy Institute of Technology - JIT", city: "Bangalore", rating: 4.0 },
  { name: "PES Institute of Technology and Management - PESITM", city: "Shimoga", rating: 4.1 },
  { name: "Bapuji Institute of Engineering and Technology - BIET", city: "Davanagere", rating: 4.1 },
  { name: "Ghousia College of Engineering - GCE", city: "Ramanagar", rating: 4.0 },
  { name: "Gopalan College of Engineering and Management - GCEM", city: "Bangalore", rating: 4.0 },
  { name: "KNS Institute of Technology - KNSIT", city: "Bangalore", rating: 4.0 },
  { name: "Maharaja Institute of Technology - MIT Mysore", city: "Mysore", rating: 4.1 },
  { name: "Reva Institute of Technology and Management - RITM", city: "Bangalore", rating: 4.0 },
  { name: "T John Institute of Technology - TJIT", city: "Bangalore", rating: 4.0 },
  { name: "Jain College of Engineering - JCE", city: "Belgaum", rating: 4.0 },
  { name: "Dayananda Sagar Institutions - DSI", city: "Bangalore", rating: 4.2 },
  { name: "Bangalore Technological Institute - BTI", city: "Bangalore", rating: 4.0 },
  { name: "Adichunchanagiri Institute of Technology - AIT", city: "Chikmagalur", rating: 4.0 },
  { name: "Channabasaveshwara Institute of Technology - CIT", city: "Tumkur", rating: 4.0 },
  { name: "GM University", city: "Davanagere", rating: 4.0 },
  { name: "Jawaharlal Nehru National College of Engineering - JNNCE", city: "Shimoga", rating: 4.1 },
  { name: "Kalpataru Institute of Technology - KIT", city: "Tiptur", rating: 3.9 },
  { name: "Mangalore Institute of Technology and Engineering - MITE", city: "Mangalore", rating: 4.1 },
  { name: "Shree Devi Institute of Technology - SDIT", city: "Mangalore", rating: 4.0 },
  { name: "Sri Vijaya Vittala Institute of Technology - VVIT", city: "Bangalore", rating: 4.0 },
  { name: "St Joseph Engineering College - SJEC", city: "Mangalore", rating: 4.2 },
  { name: "Yenepoya Institute of Technology - YIT", city: "Mangalore", rating: 4.0 },
  { name: "Sahyadri College of Engineering & Management - SCEM", city: "Mangalore", rating: 4.2 },
  { name: "Bangalore University - BU", city: "Bangalore", rating: 4.4 },
  { name: "University of Mysore - UOM", city: "Mysore", rating: 4.4 },
  { name: "Karnatak University - KU Dharwad", city: "Dharwad", rating: 4.3 },
  { name: "Gulbarga University - GU", city: "Gulbarga", rating: 4.2 },
  { name: "Mangalore University", city: "Mangalore", rating: 4.3 },
  { name: "VIT Bangalore - Vellore Institute of Technology", city: "Bangalore", rating: 4.5 },
  { name: "Amity University Bangalore", city: "Bangalore", rating: 4.3 },
  { name: "RV University - RVU", city: "Bangalore", rating: 4.4 },
  { name: "Chanakya University - CU", city: "Bangalore", rating: 4.3 },
  { name: "Atria University", city: "Bangalore", rating: 4.2 },
  { name: "Vidyashilp University - VU", city: "Bangalore", rating: 4.3 },
  { name: "National Institute of Design - NID Bangalore", city: "Bangalore", rating: 4.5 },
  { name: "Srishti Manipal Institute of Art, Design and Technology", city: "Bangalore", rating: 4.3 },
  { name: "Pearl Academy Bangalore", city: "Bangalore", rating: 4.2 },
  { name: "NIFT Bangalore", city: "Bangalore", rating: 4.6 },
  { name: "Strate School of Design", city: "Bangalore", rating: 4.2 },
  { name: "Scaler School of Technology", city: "Bangalore", rating: 4.4 },
  { name: "PW Institute of Innovation - PWIOI", city: "Bangalore", rating: 4.2 },
  { name: "TAPMI Bengaluru Campus", city: "Bangalore", rating: 4.5 },
  { name: "Symbiosis Centre for Management Studies - SCMS", city: "Bangalore", rating: 4.4 },
  { name: "NMIMS School of Law - SOL", city: "Bangalore", rating: 4.3 },
  { name: "Christ University Bangalore - Kengeri Campus", city: "Bangalore", rating: 4.4 },
  { name: "Christ University Bangalore - Yeshwanthpur Campus", city: "Bangalore", rating: 4.4 },
  { name: "St. Joseph's College of Law", city: "Bangalore", rating: 4.2 },
  { name: "RV Institute of Legal Studies - RVILS", city: "Bangalore", rating: 4.1 },
  { name: "CMR Law School", city: "Bangalore", rating: 4.0 },
  { name: "BMS College of Law - BMSCL", city: "Bangalore", rating: 4.1 },
  { name: "Dr BR Ambedkar College of Law", city: "Bangalore", rating: 4.1 },
  { name: "JSS Law College - JSSLC", city: "Mysore", rating: 4.1 },
  { name: "SDM Law College", city: "Mangalore", rating: 4.1 },
  { name: "Father Muller Medical College - FMMC", city: "Mangalore", rating: 4.5 },
  { name: "Yenepoya Medical College", city: "Mangalore", rating: 4.4 },
  { name: "Vydehi Institute of Medical Sciences and Research Centre - VIMS", city: "Bangalore", rating: 4.3 },
  { name: "Rajarajeswari Medical College And Hospital - RRMCH", city: "Bangalore", rating: 4.2 },
  { name: "Sapthagiri Institute of Medical Sciences and Research Centre - SIMSRC", city: "Bangalore", rating: 4.1 },
  { name: "MVJ Medical College and Research Hospital", city: "Bangalore", rating: 4.1 },
  { name: "Oxford Medical College Hospital and Research Centre", city: "Bangalore", rating: 4.1 },
  { name: "Akash Institute of Medical Science & Research Centre - AIMS & RC", city: "Bangalore", rating: 4.0 },
  { name: "Kanachur Institute of Medical Sciences - KIMS", city: "Mangalore", rating: 4.0 },
  { name: "Subbaiah Institute of Medical Sciences", city: "Shimoga", rating: 4.0 },
  { name: "S.S. Institute of Medical Sciences and Research Centre", city: "Davanagere", rating: 4.1 },
  { name: "KLE VK Institute of Dental Sciences", city: "Belgaum", rating: 4.2 },
  { name: "SDM College of Medical Sciences and Hospital - SDMCH", city: "Dharwad", rating: 4.3 },
  { name: "Al Ameen Medical College", city: "Bijapur", rating: 4.1 },
  { name: "Father Muller Homoeopathic Medical College", city: "Mangalore", rating: 4.1 },
  { name: "Sri Sri College of Ayurvedic Science and Research - SSCASR", city: "Bangalore", rating: 4.0 },
  { name: "SDM Institute of Ayurveda", city: "Bangalore", rating: 4.1 },
  { name: "Bapuji Ayurvedic Medical College and Hospital", city: "Bangalore", rating: 4.0 },
  { name: "SDM College of Ayurveda and Hospital - SDMCAH Hassan", city: "Hassan", rating: 4.1 },
  { name: "SDM College of Ayurveda and Hospital - SDMCAH Udupi", city: "Udupi", rating: 4.1 },
  { name: "Alva's Ayurvedic Medical College", city: "Mangalore", rating: 4.0 },
  { name: "Shree Devi College of Pharmacy", city: "Mangalore", rating: 4.0 },
  { name: "Manipal College of Nursing", city: "Manipal", rating: 4.4 },
  { name: "Father Muller College of Nursing", city: "Mangalore", rating: 4.3 },
  { name: "Krupanidhi College of Nursing - KCON", city: "Bangalore", rating: 4.1 },
  { name: "RV College of Nursing", city: "Bangalore", rating: 4.1 },
  { name: "The Oxford School of Nursing", city: "Bangalore", rating: 4.0 },
  { name: "Ramaiah Institute of Nursing Education and Research - RINER", city: "Bangalore", rating: 4.2 },
  { name: "Dayananda Sagar College of Pharmacy - DSCP", city: "Bangalore", rating: 4.1 },
  { name: "Krupanidhi College of Pharmacy - KCP", city: "Bangalore", rating: 4.1 },
  { name: "Faculty of Pharmacy, M. S. Ramaiah University", city: "Bangalore", rating: 4.2 },
  { name: "KLE College of Pharmacy - KLE COP Hubli", city: "Hubli", rating: 4.1 },
  { name: "National College of Pharmacy - NCP", city: "Shimoga", rating: 4.0 },
  { name: "Regional Institute of Education - RIE", city: "Mysore", rating: 4.3 },
  { name: "B.Ed College Jain University", city: "Bangalore", rating: 4.1 },
  { name: "New Horizon College of Education - NHCE", city: "Bangalore", rating: 4.0 },
  { name: "Lorven Teachers Training College", city: "Bangalore", rating: 4.0 },
  { name: "MES Teachers' College", city: "Bangalore", rating: 4.0 },
  { name: "Canara College", city: "Mangalore", rating: 4.2 },
  { name: "St. Agnes College", city: "Mangalore", rating: 4.3 },
  { name: "Besant Women's College", city: "Mangalore", rating: 4.1 },
  { name: "Maharani's Arts, Commerce and Management College for Women", city: "Bangalore", rating: 4.1 },
  { name: "Government Science College - GSC", city: "Bangalore", rating: 4.2 },
  { name: "National Centre for Biological Sciences - NCBS", city: "Bangalore", rating: 4.5 },
  { name: "Jawaharlal Nehru Centre for Advanced Scientific Research - JNCASR", city: "Bangalore", rating: 4.6 },
  { name: "Indian Statistical Institute - ISI Bangalore", city: "Bangalore", rating: 4.5 },
  { name: "Raman Research Institute", city: "Bangalore", rating: 4.4 },
  { name: "Institute of Bioinformatics and Applied Biotechnology - IBAB", city: "Bangalore", rating: 4.2 },
  { name: "Indian Institute for Human Settlements - IIHS", city: "Bangalore", rating: 4.2 },
  { name: "Karnataka State Open University - KSOU", city: "Mysore", rating: 4.1 },
  { name: "Tumkur University", city: "Tumkur", rating: 4.0 },
  { name: "Kuvempu University - KU", city: "Shimoga", rating: 4.1 },
  { name: "Karnataka State Law University - KSLU", city: "Hubli", rating: 4.1 },
];

async function seedColleges() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log('✅ MongoDB connected');

    // Delete existing colleges
    await College.deleteMany({});
    console.log('🗑️ Existing colleges deleted');

    // Diverse Unsplash image URLs for colleges
    const collegeImages = [
      'https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80', // University building
      'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80', // Campus architecture
      'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80', // University campus
      'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&q=80', // Modern college building
      'https://images.unsplash.com/photo-1519452575417-564c1401ecc0?w=800&q=80', // Medical college
      'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80', // Medical students
      'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80', // College library
      'https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=800&q=80', // University hall
      'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&q=80', // Medical building
      'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&q=80', // Campus exterior
      'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80', // University entrance
      'https://images.unsplash.com/photo-1568792923760-d70635a89fdc?w=800&q=80', // College campus
      'https://images.unsplash.com/photo-1590012314607-cda9d9b699ae?w=800&q=80', // Medical facility
      'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=800&q=80', // University building
      'https://images.unsplash.com/photo-1581093458791-9d42e1c5e2f9?w=800&q=80', // Modern campus
      'https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=800&q=80', // College building
      'https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80', // Classic university
      'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&q=80', // Students campus
      'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=800&q=80', // College courtyard
      'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80', // University students
    ];

    // Prepare colleges with full data
    const colleges = collegesData.map((college, index) => ({
      name: college.name,
      location: `${college.city}, Karnataka`,
      city: college.city,
      state: 'Karnataka',
      rating: college.rating,
      image: collegeImages[index % collegeImages.length],
      courses: allCourses, // All colleges have all courses
      fees: 'Contact for fees',
    }));

    // Insert all colleges
    await College.insertMany(colleges);
    console.log(`✅ ${colleges.length} colleges seeded successfully!`);

    // Show count by city
    const cityCount = await College.aggregate([
      { $group: { _id: '$city', count: { $sum: 1 } } },
      { $sort: { count: -1 } }
    ]);
    console.log('\n📊 Colleges by City:');
    cityCount.forEach(c => console.log(`  ${c._id}: ${c.count}`));

    mongoose.connection.close();
    console.log('\n✅ Done! MongoDB connection closed.');
  } catch (error) {
    console.error('❌ Error seeding colleges:', error);
    process.exit(1);
  }
}

seedColleges();
